VAGUE_PATTERNS = [
    "menu that slides out from the right",
    "menu that slides in from the side",
    "slides out from the right",
    "slides in from",
    "floating blurry",
    "frosted glass",
    "blurry popup",
    "frosted popup",
    "pinterest style",
    "pinterest grid",
    "cards in a grid",
    "masonry",
    "sticky top bar",
    "sticky header",
    "fixed header",
    "fixed top bar",
    "menu that slides",
    "popup that appears",
    "popup that shows",
    "modal that appears",
    "popup confirmation",
    "loading placeholder",
    "loading spinner",
    "spinning loading",
    "gray placeholder",
    "skeleton",
    "shimmer",
    "tabs that switch",
    "switchable sections",
    "switchable tabs",
    "expandable sections",
    "accordion",
    "breadcrumb",
    "breadcrumbs",
    "trail of links",
    "arrow links showing where",
    "three lines you tap",
    "hamburger",
    "kebab menu",
    "menu with icons",
    "page numbers at the bottom",
    "pagination",
    "sidebar with sections",
    "left sidebar",
    "side menu",
    "bar that shows up only on phones",
    "bottom tab bar",
    "menu that drops down",
    "dropdown",
    "dots at the bottom",
    "carousel indicator",
    "search bar built into",
    "nav search",
    "trail of links showing",
    "popout menu",
    "popup menu",
    "menu that pops out",
    "next and previous buttons",
    "wizard navigation",
    "footer",
    "section header on the side",
    "collapsible nav",
    "thing showing how far through",
    "progress stepper",
    "wizard indicator",
    "floating menu that follows",
    "sticky sidebar",
    "small text path",
    "side menu thats just icons",
    "icon rail",
    "tabs that scroll sideways",
    "scrollable tabs",
    "menu that opens up huge",
    "mega menu",
    "breadcrumbs but for inside",
    "bar that shows what page",
    "title bar",
    "menu thats hidden until you swipe",
    "edge drawer",
    "popup that appears when you click",
    "modal dialog",
    "blurry background behind",
    "modal backdrop",
    "scrim",
    "little box that shows up when you hover",
    "tooltip",
    "sheet that slides up from the bottom",
    "bottom sheet",
    "popup asking if you really want",
    "confirmation dialog",
    "floating box with extra info",
    "popover",
    "big popup that takes over",
    "full screen modal",
    "frosted glass popup",
    "glassmorphic",
    "lightbox that shows images",
    "image lightbox",
    "popup that shows notifications",
    "toast notification",
    "side panel that slides in from the right",
    "right drawer",
    "dialog box that asks you to fill in",
    "input dialog",
    "small popup near where you clicked",
    "contextual popover",
    "warning message that pops up",
    "alert dialog",
    "cookie consent",
    "consent banner",
    "loading overlay",
    "panel for quick settings",
    "settings panel",
    "floating card that previews",
    "link preview",
    "popup video player",
    "video modal",
    "overlay that blocks the page",
    "blocking overlay",
    "popup when you long press",
    "context menu",
    "dialog for picking a date",
    "date picker",
    "dropdown that appears below",
    "search suggestions",
    "autocomplete",
    "terms and conditions popup",
    "legal consent",
    "floating help bubble",
    "help tooltip",
    "big section at the top",
    "hero section",
    "cards arranged in a grid",
    "card grid",
    "two column layout",
    "split content",
    "section with cards showing features",
    "feature grid",
    "full width colored band",
    "full width banner",
    "section where you put logos",
    "logo strip",
    "big image that takes up the whole background",
    "full bleed",
    "pricing cards side by side",
    "pricing table",
    "section at the very bottom",
    "footer section",
    "three equal boxes in a row",
    "three column layout",
    "narrow centered content",
    "content container",
    "section with a dark background",
    "dark section",
    "sticky panel on the side",
    "section asking people to sign up",
    "call to action",
    "cta",
    "cards that show blog posts",
    "blog card",
    "image on the left with text on the right",
    "media object",
    "row of stats",
    "stats bar",
    "section with a video in the background",
    "video background",
    "alternating image and text",
    "alternating feature",
    "small cards with icons",
    "icon card",
    "full height section",
    "full viewport",
    "testimonials in a row",
    "testimonial grid",
    "section with a form on one side",
    "split form",
    "big number counters",
    "animated stats",
    "section with team member photos",
    "team grid",
    "text box you type into",
    "text input",
    "big text box for longer writing",
    "textarea",
    "dropdown where you pick one",
    "select dropdown",
    "checkboxes you tick",
    "checkbox group",
    "on off switch",
    "toggle switch",
    "slider you drag",
    "range slider",
    "star rating",
    "date picker calendar",
    "file upload",
    "search box",
    "search bar",
    "button that submits",
    "submit button",
    "color picker",
    "tags you can add",
    "tag input",
    "chip input",
    "number input with plus and minus",
    "number stepper",
    "phone number input",
    "address form",
    "credit card input",
    "payment card",
    "terms checkbox you have to tick",
    "consent checkbox",
    "search with filters",
    "filtered search",
    "password strength",
    "two options you can switch between",
    "segmented control",
    "form that appears inline",
    "inline form",
    "rich text editor",
    "wysiwyg",
    "multi step form",
    "wizard form",
]


def contains_vague_phrase(text):
    if not text or not text.strip():
        return False
    text_lower = text.lower()
    for pattern in VAGUE_PATTERNS:
        if pattern in text_lower:
            return True
    return False

